- name: Configure hosts
  hosts: security_group_enterprise_example_{{ lookup('env','DEMO_NAME') }}
  tasks:
  - name: Wait 5 minutes for Conjur to be healthy
    health_check: url=https://{{ ec2_public_dns_name }}/health delay_between_tries=10 max_retries=30
  
  - name: Fetch the CA certificate
    fetch: src=/etc/conjur.pem dest=/etc/conjur/ flat=yes

  - name: Create the Conjur configuration file
    connection: local
    template: src=../templates/conjur.conf.j2 dest=/etc/conjur/conjur.conf
    vars:
      hostname: "{{ ec2_public_dns_name }}"
    
  - name: Create the Conjur identity file
    connection: local
    template: src=../templates/netrc.j2 dest=/etc/conjur/.conjurrc mode=0640
    vars:
      hostname: "{{ ec2_public_dns_name }}"
