- name: Configure hosts
  hosts: security_group_enterprise_example_{{ lookup('env','DEMO_NAME') }}
  tasks:
  - name: Wait for Conjur to be healthy
    health_check: url=https://{{ ec2_public_dns_name }}/health delay_between_tries=20 max_retries=30
  
  - name: Fetch the CA certificate
    fetch: src=/etc/conjur.pem dest=/etc/conjur/conjur-{{ lookup('env','DEMO_NAME') }}.pem flat=yes

  - name: Create the Conjur configuration file
    connection: local
    template: src=../templates/conjur.conf.j2 dest=/etc/conjur/conjur.conf
    vars:
      account:  "{{ lookup('env','DEMO_NAME') }}"
      hostname: "{{ ec2_public_dns_name }}"
