---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create security group ee_ansible_managed_{{ lookup('env','DEMO_NAME') }}
    ec2_group:
      name: ee_ansible_managed_{{ lookup('env','DEMO_NAME') }}
      description: "Security group for Ansible-managed host"
      region: us-east-1
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
    register: demo_sg
  
  - name: Launch Instance
    ec2:
      key_name: "{{ lookup('env','SSH_KEY_NAME') }}"
      instance_type: m3.medium
      region: us-east-1
      image: ami-fce3c696
      wait: yes
      count: 1
      group_id: "{{demo_sg.group_id}}"
      
    register: ec2
  
  - name: Wait for SSH
    local_action: wait_for host={{item.public_ip}} port=22 delay=15 state=started
    with_items: "{{ec2.instances}}"
    
  - name: Load and populate Conjur policy
    local_action: script /src/ansible/register_host.sh {{item.id}} {{item.public_ip}}
    with_items: "{{ec2.instances}}"
