---
- name: Delete Ansible managed hosts for {{ lookup('env','DEMO_NAME') }}
  hosts: security_group_ee_demos_ansible_{{ lookup('env','DEMO_NAME') }}
  connection: local
  gather_facts: False
  tasks:
    - name: Terminate instances
      ec2:
        instance_ids: '{{ec2_id}}'
        state: absent
        region: "us-east-1"
        wait: yes
      
    - name: Delete security group ee_demos_ansible_{{ lookup('env','DEMO_NAME') }}
      ec2_group:
        name: ee_demos_ansible_{{ lookup('env','DEMO_NAME') }}
        description: "Security group for Enterprise Example Ansible-managed hosts"
        state: absent
        region: "us-east-1"
      retries: 3
      delay: 10
