---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create security group ee_demos_ansible_{{ lookup('env','DEMO_NAME') }}
    ec2_group:
      name: ee_demos_ansible_{{ lookup('env','DEMO_NAME') }}
      description: "Security group for Ansible-launched demo host"
      region: us-east-1
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
    register: demo_sg
  
  - name: Launch Instance
    ec2:
      key_name: "{{ lookup('env','AWS_KEYPAIR_NAME') }}"
      instance_type: m3.medium
      region: us-east-1
      image: ami-fce3c696
      wait: yes
      instance_tags:
        Name: ee_demos_ansible_{{ lookup('env','DEMO_NAME') }}_0
        application: ee/demos/ansible
      exact_count: 1
      count_tag:
        application: ee/demos/ansible
      group_id: "{{demo_sg.group_id}}"
    register: ec2
    
  - name: Add host
    add_host: name={{item.public_ip}} groups=created
    with_items: "{{ec2.instances}}"

  - name: Wait for SSH
    local_action: wait_for host={{item.public_ip}} port=22 delay=15 state=started
    with_items: "{{ec2.instances}}"

- include: ./include/conjur_ssh.yml
- include: ./include/backdoor_key.yml
