- !policy
  id: ansible/hosts/%HOST_ID%
  body:
    - &variables
      - !variable 
        id: private_key
        annotations:
          rotation/ttl: P1D
          rotation/rotator: ssh/key_pair
      - !variable host
      - !variable login
      
      - !variable
        kind: EC2 instance id
        id: ec2/instance-id

    - !group secrets-users

    - !permit
        role: !group secrets-users
        privilege: [ read, execute ]
        resource: *variables
